import type { Bundle, Part, Procedure, Structure } from './catalog';

const source = (title:string,slug:string,scope:string) => ({ title, url:`https://www.parktool.com/en-us/blog/repair-help/${slug}`,scope });
const recipes:Procedure[] = [
 {id:'frame',title:'Telaio e parti permanenti',steps:['Rimuovi tutti i gruppi fissati al telaio seguendo le rispettive schede.','Il telaio saldato rimane un solo componente. I tubi non si separano durante la manutenzione. Ispeziona crepe e corrosione prima del restauro.'],tools:[{name:'Cavalletto e luce di ispezione',size:'Compatibili con il telaio',certainty:'indicative'}],warnings:['Non separare saldature, brasature o inserti permanenti.'],sources:[]},
 {id:'wheel',title:'Rimuovere una ruota con asse a dadi',steps:['Sostieni la bici e libera il freno se impedisce il passaggio del pneumatico.','Allenta i dadi dell’asse. Annota l’ordine delle rondelle. Per la ruota posteriore, libera la catena dal pignone.','Sfila la ruota dai forcellini e conserva dadi e rondelle in una vaschetta etichettata.'],tools:[{name:'Chiave per dadi dell’asse',size:'Spesso 15 mm; misurare il dado reale',certainty:'indicative'}],warnings:['La misura del dado dipende dal mozzo. Il serraggio al rimontaggio va verificato nel manuale.'],sources:[]},
 {id:'tire',title:'Pneumatico, camera e nastro',steps:['Togli la ruota e sgonfia completamente la camera.','Spingi i talloni verso il centro del cerchio, solleva un tallone con levagomme e sfila la camera.','Estrai il secondo tallone. Rimuovi il nastro solo se va sostituito o devi accedere ai nippli.'],tools:[{name:'Levagomme',size:'In plastica, per copertoncini',certainty:'indicative'},{name:'Pompa',size:'Testa compatibile con la valvola reale',certainty:'unknown'}],warnings:['Non usare cacciaviti per sollevare il tallone. Il tipo di valvola va identificato.'],sources:[]},
 {id:'hub',title:'Aprire un mozzo a coni e sfere',steps:['Rimuovi la ruota; lavora sopra una vaschetta per recuperare le sfere.','Fotografa l’ordine di dado, rondella, distanziale e cono. Tieni fermo il cono con una chiave sottile e allenta il controdado sul lato appropriato.','Svita il cono, sfila l’asse e recupera le sfere separando i lati. Conta e misura le sfere della bici reale.','Le piste integrate nel corpo del mozzo rimangono solidali. Controlla usura e vaiolature.'],tools:[{name:'Chiave sottile per coni',size:'Da misurare: tipicamente 13–17 mm',certainty:'indicative'},{name:'Chiave per controdado',size:'Da misurare sul mozzo',certainty:'unknown'},{name:'Calibro e vaschetta',size:'Per diametro delle sfere e ordine dei pezzi',certainty:'indicative'}],warnings:['Numero e diametro delle sfere qui sono illustrativi. Il precarico dei coni richiede regolazione dopo il rimontaggio.'],sources:[source('Park Tool · Mozzi a coni','hub-overhaul-and-adjustment','Procedura generale; non identifica questo mozzo né le sue misure.')]},
 {id:'spoke',title:'Separare raggi e nippli',steps:['Rimuovi ruota, pneumatico, camera e nastro. Fotografa incrocio e orientamento dei raggi.','Riduci gradualmente e uniformemente la tensione dei raggi. Svita il nipplo del raggio interessato.','Sfila il raggio dalla flangia. La ricostruzione della ruota richiede centratura, campanatura e controllo della tensione.'],tools:[{name:'Chiave tiraraggi',size:'Apertura da misurare: ad esempio 3,23 / 3,30 / 3,45 mm',certainty:'indicative'},{name:'Centraruote e tensiometro',size:'Compatibili con ruota e raggi',certainty:'unknown'}],warnings:['Non tagliare o allentare un raggio sotto forte tensione. Prima di usare la bici, fai verificare la ruota ricostruita.'],sources:[]},
 {id:'headset',title:'Serie sterzo filettata e forcella',steps:['Libera cavi e attacco manubrio. Sostieni la forcella dal basso.','Tieni ferma la calotta superiore e allenta il controdado. Rimuovi rondella e calotta annotando l’ordine.','Sfila la forcella lentamente; recupera le sfere o le gabbiette superiori e inferiori.','L’estrazione delle calotte pressate e della pista sulla forcella richiede estrattori adatti; non improvvisare colpi sul telaio.'],tools:[{name:'Chiavi per serie sterzo',size:'Spesso 30 / 32 / 36 mm: da misurare',certainty:'indicative'},{name:'Estrattore calotte e pista forcella',size:'Compatibile con diametri reali',certainty:'unknown'}],warnings:['Sostieni la forcella per evitare che cada. Le sfere libere non devono andare perse.'],sources:[source('Park Tool · Serie sterzo filettata','threaded-headset-service','Procedura generale; diametri e quantità da verificare.')]},
 {id:'cockpit',title:'Manubrio e attacco a espansore',steps:['Scollega o allenta i comandi che impediscono la rimozione.','Allenta di pochi giri la vite dell’espansore. Libera il cuneo con un colpetto controllato usando una protezione sulla testa, se necessario.','Estrai l’attacco e conserva vite e cuneo. Allenta il morsetto per separare il manubrio.'],tools:[{name:'Chiave esagonale',size:'Spesso 6 mm per espansore; verificare anche il morsetto',certainty:'indicative'},{name:'Mazzuolo e protezione',size:'Testa morbida',certainty:'indicative'}],warnings:['Non forzare un attacco bloccato dalla corrosione. Rispetta la tacca di inserimento minimo al rimontaggio.'],sources:[]},
 {id:'seat',title:'Sella e reggisella',steps:['Segna l’altezza e fotografa l’orientamento del morsetto della sella.','Allenta il collare del telaio e sfila il reggisella.','Allenta la vite del morsetto superiore e separa piastre e sella. La sella cucita o rivettata non si apre per la manutenzione ordinaria.'],tools:[{name:'Chiave per collare e morsetto',size:'Esagonale o chiave aperta: misurare le teste reali',certainty:'unknown'}],warnings:['La corrosione può bloccare il reggisella. Non torcere senza aver verificato materiale e metodo.'],sources:[]},
 {id:'crank',title:'Pedivelle a perno quadro',steps:['Rimuovi il tappo parapolvere, se presente.','Svita la vite o il dado centrale ed estrai l’eventuale rondella.','Avvita completamente il corpo dell’estrattore nella pedivella; usa una punta compatibile con il perno quadro.','Avvita il pistone dell’estrattore per sfilare la pedivella. Per le viti della corona, controtrattieni la bussola.'],tools:[{name:'Chiave per vite pedivella',size:'Esagonale 8 mm o bussola 14 mm: verificare la versione',certainty:'indicative'},{name:'Estrattore pedivelle',size:'Compatibile con perno quadro e filettatura della pedivella',certainty:'unknown'},{name:'Chiave viti corona e controchiave',size:'Spesso esagonale 5 mm, da verificare',certainty:'indicative'}],warnings:['Rimuovi le rondelle prima di usare l’estrattore. Un estrattore parzialmente avvitato può danneggiare il filetto.'],sources:[source('Park Tool · Pedivelle in tre pezzi','crank-removal-and-installation-three-piece','Perno quadro e scelta dell’estrattore; non certifica le misure della demo.')]},
 {id:'bb',title:'Movimento centrale a calotte e sfere',steps:['Togli catena e pedivelle. Identifica lo standard della filettatura prima di applicare forza.','Allenta la ghiera lato sinistro, poi svita la calotta regolabile. Recupera le sfere.','Estrai il perno e le sfere dell’altro lato. Rimuovi la calotta fissa solo con un utensile adeguato.','Nel BSA la calotta destra si svita in senso orario, vista dal lato destro esterno. Nello standard italiano la destra si svita in senso antiorario.'],tools:[{name:'Chiave a settore per ghiera',size:'Profilo compatibile con la ghiera',certainty:'unknown'},{name:'Chiave calotta regolabile',size:'A perni o piatti, secondo il componente',certainty:'unknown'},{name:'Chiave calotta fissa',size:'Spesso 36 mm; da misurare',certainty:'indicative'}],warnings:['Il senso di svitamento cambia con lo standard. Questa demo illustra BSA, non tutte le biciclette.'],sources:[source('Park Tool · Movimento a calotte','bottom-bracket-service-adjustable-cup-and-cone','Procedura generale per sistemi regolabili, non per cartucce sigillate.')]},
 {id:'pedal',title:'Pedali e cuscinetti',steps:['Individua i pedali L e R. Guardando il pedale dall’esterno del suo lato: il destro si svita in senso antiorario, il sinistro in senso orario.','Usa una chiave pedali sui piatti o la chiave esagonale prevista dal produttore.','Per un pedale revisionabile, rimuovi il tappo e apri il sistema di controdado e cono sopra una vaschetta. Segui il manuale del pedale per estrarre asse e sfere.'],tools:[{name:'Chiave pedali',size:'Tipicamente 15 mm; verificare i piatti',certainty:'indicative'},{name:'Chiave esagonale alternativa',size:'6 o 8 mm secondo il pedale',certainty:'indicative'},{name:'Utensili interni del pedale',size:'Specifici del modello; non identificati',certainty:'unknown'}],warnings:['Non usare una chiave sottile per coni come chiave pedali. Alcuni pedali non sono revisionabili.'],sources:[source('Park Tool · Pedali','pedal-installation-and-removal','Sensi di filettatura e varianti di utensili.')]},
 {id:'chain',title:'Catena e piccoli componenti',steps:['Rimuovi la catena aprendo la falsamaglia compatibile oppure espellendo un perno con uno smagliacatena.','Le piastre, i rulli e i perni sono mostrati separatamente per comprenderne la struttura.','La separazione integrale di tutti i perni è un’analisi didattica: non è una normale procedura di manutenzione. Piastrine e perni smontati non vanno riutilizzati senza prescrizione del produttore.'],tools:[{name:'Smagliacatena',size:'Compatibile con la larghezza e il numero di velocità',certainty:'unknown'},{name:'Pinza falsamaglia, se presente',size:'Compatibile con il collegamento reale',certainty:'unknown'}],warnings:['Alcuni collegamenti richiedono perni o falsamaglie nuovi. La catena della demo non rappresenta una marca specifica.'],sources:[]},
 {id:'freewheel',title:'Ruota libera e pignone',steps:['Rimuovi la ruota e l’asse se necessario per l’inserimento dell’utensile.','Identifica il profilo della ruota libera. Inserisci l’estrattore adatto e controtrattieni la ruota.','Svita la ruota libera in senso antiorario guardandola dal lato del pignone. L’apertura interna richiede il manuale specifico.'],tools:[{name:'Estrattore ruota libera',size:'Profilo da identificare; non uguale a un estrattore cassetta',certainty:'unknown'},{name:'Chiave per estrattore',size:'Secondo l’utensile scelto',certainty:'unknown'}],warnings:['Meccanismo interno non ricostruito nella demo: non assumere quantità di cricchetti, molle e sfere.'],sources:[]},
 {id:'brake',title:'Freno a pinza e comando',steps:['Allenta il fissaggio del cavo e libera la tensione. Fotografa il percorso del cavo.','Rimuovi pattini, rondelle e dadi conservando l’ordine. Scollega il dado di fissaggio della pinza al telaio.','Solo per una pinza revisionabile, separa bracci, perno e molla secondo il manuale. Per le leve, libera il cavo e il morsetto.'],tools:[{name:'Chiavi per fissaggi del freno',size:'Esagonali o chiavi aperte, da misurare',certainty:'unknown'},{name:'Tronchese per cavi e guaine',size:'Specifico per cavi bici',certainty:'indicative'}],warnings:['Freni: prima della prova su strada sono necessari controllo del serraggio, allineamento dei pattini e prova di funzionamento. Non tagliare un cavo che vuoi riutilizzare.'],sources:[]}
];

const parts:Part[]=[]; const mint='#77b9ad',silver='#bcc5c9',dark='#293437',rubber='#263133';
function add(id:string,name:string,group:string,recipe:string,kind:Part['geometry']['kind'],position:number[],size:number[],description:string,opts:Partial<Part> & {end?:number[],rotation?:number[],color?:string}={}) {
 const {end,rotation,color,...rest}=opts;
 parts.push({id,name,group,description,procedureId:recipe,dependsOn:[],evidence:'indicative',serviceability:'serviceable',geometry:{kind,position:position as [number,number,number],size:size as [number,number,number],end:end as [number,number,number],rotation:rotation as [number,number,number],color:color||silver},explode:[position[0]*.42,position[1]*.24,position[2]===0 ? ((parts.length%2?1:-1)*.22) : position[2]*1.9],...rest});
}
function tube(id:string,name:string,g:string,r:string,a:number[],b:number[],radius:number,description:string,color=silver,dependsOn:string[]=[]) {add(id,name,g,r,'tube',a,[radius,0,0],description,{end:b,color,dependsOn});}
function ball(id:string,name:string,g:string,r:string,p:number[],radius:number,desc:string,deps:string[]){add(id,name,g,r,'ball',p,[radius,0,0],desc,{dependsOn:deps});}

const BB=[-.28,.34,0],rear=[-.93,.57,0],front=[1.01,.57,0],seat=[-.47,1.29,0],head=[.66,1.30,0];
// One welded frame: procedural tubes share the same selectable part ID in the viewer.
add('frame','Telaio saldato','Telaio','frame','tube',BB,[.026,0,0],'Struttura portante: collega ruote, sterzo, sella e trasmissione. I tubi saldati sono inseparabili nella manutenzione ordinaria.',{end:seat,color:mint,serviceability:'inseparable'});
// Supplementary geometry is generated by the viewer for this part; no duplicate welded "pieces".
tube('fork','Forcella','Sterzo','headset',[.70,1.15,0],front,.019,'Sostiene la ruota anteriore e ruota nella serie sterzo.',mint,['head-locknut','head-washer','head-upper-cup']);
tube('stem','Attacco manubrio a espansore','Manubrio','cockpit',[.67,1.40,0],[.78,1.58,0],.018,'Collega il manubrio alla forcella tramite un cuneo interno.',silver,['stem-bolt']);
add('stem-bolt','Vite espansore','Manubrio','cockpit','cylinder',[.67,1.53,0],[.006,.15,0],'Tira il cuneo e blocca l’attacco dentro il cannotto.');
add('stem-wedge','Cuneo espansore','Manubrio','cockpit','cylinder',[.67,1.37,0],[.014,.035,0],'Si espande contro il cannotto quando la vite viene stretta.',{dependsOn:['stem-bolt','stem']});
tube('handlebar','Manubrio','Manubrio','cockpit',[.79,1.57,-.29],[.79,1.57,.29],.013,'Appoggio delle mani e leva con cui orienti la ruota.',silver,['bar-bolt']);
add('bar-bolt','Vite morsetto manubrio','Manubrio','cockpit','cylinder',[.80,1.56,.035],[.005,.05,0],'Chiude il morsetto che trattiene il manubrio.');
for(const side of [-1,1]) {tube(`grip-${side}`,`Manopola ${side<0?'sinistra':'destra'}`,'Manubrio','cockpit',[.79,1.57,side*.19],[.79,1.57,side*.30],.020,'Rivestimento di presa per la mano.',rubber);add(`lever-${side}`,`Leva freno ${side<0?'sinistra':'destra'}`,'Freni','brake','box',[.85,1.53,side*.17],[.085,.022,.085],'Trasforma la forza della mano in trazione del cavo.',{color:dark});add(`lever-bolt-${side}`,'Vite morsetto leva','Freni','brake','cylinder',[.79,1.55,side*.17],[.004,.032,0],'Fissa la leva al manubrio.');}
tube('seatpost','Reggisella','Sella','seat',[-.47,1.20,0],[-.52,1.51,0],.016,'Sostiene la sella e ne regola l’altezza.',silver,['seat-clamp-bolt']);
add('seat-clamp-bolt','Vite collare reggisella','Sella','seat','cylinder',[-.47,1.27,.027],[.005,.06,0],'Stringe il tubo del telaio attorno al reggisella.');
add('seat-clamp-nut','Dado collare reggisella','Sella','seat','cylinder',[-.47,1.27,-.027],[.008,.008,0],'Controparte filettata della vite del collare.',{dependsOn:['seat-clamp-bolt']});
add('saddle','Sella completa','Sella','seat','box',[-.52,1.54,0],[.24,.06,.15],'Sostiene il peso del ciclista. Rivestimento e scafo non si separano nella manutenzione ordinaria.',{color:dark,dependsOn:['saddle-bolt'],serviceability:'inseparable'});
add('saddle-bolt','Vite morsetto sella','Sella','seat','cylinder',[-.52,1.48,0],[.005,.06,0],'Blocca l’inclinazione della sella e le sue guide.');
for(const i of [-1,1])add(`saddle-plate-${i}`,`Piastra morsetto ${i<0?'inferiore':'superiore'}`,'Sella','seat','box',[-.52,1.47+i*.01,0],[.05,.009,.08],'Serraggio delle guide della sella.',{dependsOn:['saddle-bolt']});
for(const [id,y,r]of [['head-locknut',1.40,.030],['head-washer',1.37,.028],['head-upper-cup',1.34,.032],['head-lower-cup',1.16,.032],['head-crown-race',1.13,.027]] as const)add(id,({'head-locknut':'Controdado serie sterzo','head-washer':'Rondella con linguetta','head-upper-cup':'Calotta superiore','head-lower-cup':'Calotta inferiore','head-crown-race':'Pista sulla forcella'})[id],'Sterzo','headset','ring',[.68,y,0],[r,.007,0],'Elemento della serie sterzo: contiene o regola le piste su cui ruotano i cuscinetti.',{rotation:[Math.PI/2,0,0],dependsOn:id==='head-locknut'?['stem']:id==='head-washer'?['head-locknut']:id==='head-upper-cup'?['head-washer']:['fork'],serviceability:id==='head-lower-cup'||id==='head-crown-race'?'specialist':'serviceable'});
for(const [layer,y]of [[0,1.32],[1,1.18]])for(let i=0;i<16;i++){let a=i*Math.PI/8;ball(`head-ball-${layer}-${i}`,`Sfera sterzo ${layer?'inferiore':'superiore'} · ${i+1}`,'Sterzo','headset',[.68+Math.cos(a)*.023,y,Math.sin(a)*.023],.0045,'Elemento volvente che riduce l’attrito tra forcella e telaio. Quantità illustrativa.',['head-upper-cup']);}

for(const [tag,pos]of [['front',front],['rear',rear]] as const){ const g=tag==='front'?'Ruota anteriore':'Ruota posteriore',x=pos[0],y=pos[1];
 add(`${tag}-tire`,'Pneumatico',g,'tire','ring',[x,y,0],[.325,.025,0],'Parte in gomma a contatto con la strada.',{color:rubber,dependsOn:[`${tag}-axle-nut-r`]});
 add(`${tag}-tube`,'Camera d’aria',g,'tire','ring',[x,y,0],[.318,.012,0],'Contiene l’aria sotto pressione.',{color:'#535e63',dependsOn:[`${tag}-tire`]});
 add(`${tag}-rim`,'Cerchio',g,'spoke','ring',[x,y,0],[.299,.012,0],'Anello su cui si montano pneumatico e raggi.',{dependsOn:[`${tag}-tape`],serviceability:'specialist'});
 add(`${tag}-tape`,'Nastro paranippli',g,'tire','ring',[x,y,0],[.299,.004,0],'Protegge la camera dalle estremità dei raggi e dai fori del cerchio.',{color:'#ba925c',dependsOn:[`${tag}-tube`]});
 tube(`${tag}-axle`,'Asse del mozzo',g,'hub',[x,y,-.10],[x,y,.10],.006,'Perno che collega la ruota al telaio.',silver,[`${tag}-cone-r`]);
 add(`${tag}-hub`,'Corpo mozzo con piste integrate',g,'hub','cylinder',[x,y,0],[.033,.095,0],'Corpo rotante che collega le flange ai raggi. Le piste integrate non si estraggono.',{rotation:[Math.PI/2,0,0],dependsOn:[`${tag}-axle`],serviceability:'inseparable'});
 for(const [side,z]of [['l',-.08],['r',.08]]as const){
  add(`${tag}-axle-nut-${side}`,`Dado asse ${side==='l'?'sinistro':'destro'}`,g,'wheel','cylinder',[x,y,z*1.18],[.012,.012,0],'Blocca l’asse nei forcellini.',{rotation:[Math.PI/2,0,0]});
  add(`${tag}-washer-${side}`,'Rondella asse',g,'wheel','ring',[x,y,z],[.012,.003,0],'Distribuisce il carico del dado.',{dependsOn:[`${tag}-axle-nut-${side}`]});
  add(`${tag}-locknut-${side}`,'Controdado del cono',g,'hub','cylinder',[x,y,z*.83],[.012,.008,0],'Mantiene la regolazione del cono.',{rotation:[Math.PI/2,0,0],dependsOn:[`${tag}-axle-nut-${side}`]});
  add(`${tag}-cone-${side}`,'Cono cuscinetto',g,'hub','cylinder',[x,y,z*.62],[.013,.014,0],'Pista regolabile che appoggia sulle sfere.',{rotation:[Math.PI/2,0,0],dependsOn:[`${tag}-locknut-${side}`]});
  add(`${tag}-seal-${side}`,'Parapolvere mozzo',g,'hub','ring',[x,y,z*.48],[.026,.004,0],'Riduce l’ingresso di sporco nei cuscinetti.',{color:dark,dependsOn:[`${tag}-cone-${side}`]});
  for(let i=0;i<9;i++){let a=i*Math.PI*2/9;ball(`${tag}-ball-${side}-${i}`,`Sfera mozzo ${side==='l'?'sinistra':'destra'} · ${i+1}`,g,'hub',[x+Math.cos(a)*.022,y+Math.sin(a)*.022,z*.35],.004,'Elemento volvente del cuscinetto. Numero e diametro puramente illustrativi.',[`${tag}-cone-${side}`]);}
 }
 for(let i=0;i<32;i++){let a=i*Math.PI/16, b=a+(i%2?-.28:.28),z=i%2?.035:-.035;const endpoint=[x+Math.cos(a)*.297,y+Math.sin(a)*.297,0];tube(`${tag}-spoke-${i}`,`Raggio · ${i+1}`,g,'spoke',[x+Math.cos(b)*.033,y+Math.sin(b)*.033,z],endpoint,.0017,'Elemento in trazione che collega mozzo e cerchio.',silver,[`${tag}-nipple-${i}`]);add(`${tag}-nipple-${i}`,`Nipplo · ${i+1}`,g,'spoke','cylinder',endpoint,[.0038,.012,0],'Dado filettato con cui si regola la tensione del raggio.',{rotation:[0,0,a-Math.PI/2],dependsOn:[`${tag}-tape`],serviceability:'specialist'});}
}

for(const [id,z]of [['bb-left-cup',-.049],['bb-right-cup',.049],['bb-lockring',-.060]]as const)add(id,id==='bb-lockring'?'Ghiera movimento centrale':`Calotta ${z<0?'sinistra regolabile':'destra fissa'}`,'Movimento centrale','bb','ring',[-.28,.34,z],[.028,.005,0],'Contiene o regola il cuscinetto del movimento centrale.',{dependsOn:id==='bb-lockring'?['crank-l']:id==='bb-left-cup'?['bb-lockring']:['bb-spindle']});
tube('bb-spindle','Perno quadro','Movimento centrale','bb',[-.28,.34,-.09],[-.28,.34,.09],.009,'Trasmette la rotazione tra le due pedivelle.',silver,['bb-left-cup']);
for(const [side,z]of [['l',-.036],['r',.036]]as const)for(let i=0;i<11;i++){let a=i*Math.PI*2/11;ball(`bb-ball-${side}-${i}`,`Sfera movimento ${side==='l'?'sinistra':'destra'} · ${i+1}`,'Movimento centrale','bb',[-.28+Math.cos(a)*.019,.34+Math.sin(a)*.019,z],.004,'Sfera del cuscinetto: sostiene il perno e ne permette la rotazione. Quantità illustrativa.',['bb-spindle']);}
for(const [side,z,dir]of [['l',-.095,1],['r',.095,-1]]as const){
 tube(`crank-${side}`,`Pedivella ${side==='l'?'sinistra':'destra'}`,'Trasmissione','crank',[-.28,.34,z],[-.28+dir*.11,.34+dir*.12,z],.014,'Leva che trasmette la forza del piede al perno quadro.',silver,[`crank-bolt-${side}`]);
 add(`crank-bolt-${side}`,'Vite centrale pedivella','Trasmissione','crank','cylinder',[-.28,.34,z*1.15],[.008,.023,0],'Tiene la pedivella serrata sul perno quadro.',{rotation:[Math.PI/2,0,0],dependsOn:[`crank-cap-${side}`]});
 add(`crank-cap-${side}`,'Tappo parapolvere pedivella','Trasmissione','crank','cylinder',[-.28,.34,z*1.29],[.012,.004,0],'Protegge il fissaggio centrale.',{rotation:[Math.PI/2,0,0],color:dark});
 const p=[-.28+dir*.11,.34+dir*.12,z*1.90];add(`pedal-body-${side}`,`Corpo pedale ${side==='l'?'sinistro':'destro'}`,'Pedali','pedal','box',p,[.085,.030,.10],'Piattaforma su cui appoggia il piede. Versione interna illustrativa.',{color:dark});
 tube(`pedal-spindle-${side}`,'Asse pedale','Pedali','pedal',[p[0],p[1],z],[p[0],p[1],z*2.1],.005,'Perno filettato avvitato alla pedivella.',silver,[`pedal-body-${side}`]);
 for(const [type,offset]of [['cap',.05],['locknut',.04],['cone',.025]]as const)add(`pedal-${type}-${side}`,type==='cap'?'Tappo pedale':type==='locknut'?'Controdado pedale':'Cono pedale','Pedali','pedal','cylinder',[p[0],p[1],p[2]+Math.sign(z)*offset],[type==='cap'?.012:.007,.008,0],'Parte del sistema di regolazione e protezione del pedale revisionabile.',{rotation:[Math.PI/2,0,0],dependsOn:type==='cap'?[]:[`pedal-cap-${side}`]});
 for(let i=0;i<8;i++)for(const j of [-1,1]){let a=i*Math.PI/4;ball(`pedal-ball-${side}-${j}-${i}`,`Sfera pedale · ${j<0?'interna':'esterna'} ${i+1}`,'Pedali','pedal',[p[0]+Math.cos(a)*.009,p[1]+Math.sin(a)*.009,p[2]+j*.022],.0028,'Elemento volvente del pedale revisionabile. Geometria illustrativa.',[`pedal-cone-${side}`]);}
}
add('chainring','Corona','Trasmissione','crank','ring',[-.28,.34,.084],[.108,.011,0],'Ruota dentata che trascina la catena.',{dependsOn:['chain-link','crank-r']});
for(let i=0;i<5;i++){let a=i*Math.PI*2/5;add(`chainring-bolt-${i}`,`Vite corona · ${i+1}`,'Trasmissione','crank','cylinder',[-.28+Math.cos(a)*.065,.34+Math.sin(a)*.065,.096],[.004,.018,0],'Fissa la corona alla pedivella.',{rotation:[Math.PI/2,0,0]});add(`chainring-nut-${i}`,`Bussola corona · ${i+1}`,'Trasmissione','crank','cylinder',[-.28+Math.cos(a)*.065,.34+Math.sin(a)*.065,.076],[.005,.012,0],'Controparte filettata della vite corona.',{rotation:[Math.PI/2,0,0],dependsOn:[`chainring-bolt-${i}`]});}
add('freewheel','Ruota libera monovelocità (gruppo)','Trasmissione','freewheel','ring',[-.93,.57,.07],[.050,.014,0],'Permette alla ruota di continuare a girare senza muovere i pedali. Interni non modellati in questa demo.',{dependsOn:['rear-axle-nut-r','chain-link'],serviceability:'specialist'});
add('chain-link','Collegamento catena (esempio)','Catena','chain','box',[-.6,.53,.086],[.013,.006,.01],'Punto di apertura illustrativo: identifica perno o falsamaglia effettivi prima di intervenire.',{color:dark});
// Individual rollers, pins and paired plates along a simplified oval chain path.
for(let i=0;i<72;i++){const a=i/72*Math.PI*2,x=-.605+Math.cos(a)*.385,y=.455+Math.sin(a)*.102;add(`chain-roller-${i}`,`Rullo catena · ${i+1}`,'Catena','chain','cylinder',[x,y,.086],[.004,.007,0],'Ruota sul perno e appoggia sui denti di corona e pignone.',{rotation:[Math.PI/2,0,0],color:dark,dependsOn:['chain-link'],serviceability:'specialist'});add(`chain-pin-${i}`,`Perno catena · ${i+1}`,'Catena','chain','cylinder',[x,y,.086],[.002,.013,0],'Rivetto che unisce le piastrine; non presumere che sia riutilizzabile.',{rotation:[Math.PI/2,0,0],dependsOn:['chain-link'],serviceability:'specialist'});for(const side of [-1,1])add(`chain-plate-${i}-${side}`,`Piastrina ${i%2?'esterna':'interna'} · ${i+1} / ${side<0?'S':'D'}`,'Catena','chain','box',[x,y,.086+side*.006],[.016,.005,.0015],'Elemento laterale della maglia. Le boccole possono essere integrate nelle piastrine, secondo il modello.',{color:dark,rotation:[0,0,Math.atan2(.102*Math.cos(a),-.385*Math.sin(a))],dependsOn:[`chain-pin-${i}`],serviceability:'specialist'});}

for(const [tag,x,y]of [['front',.81,1.04],['rear',-.81,1.00]]as const){
for(const side of [-1,1]){tube(`${tag}-brake-arm-${side}`,`Braccio pinza ${side<0?'sinistro':'destro'}`,'Freni','brake',[x,y,.02],[x+side*.08,y-.07,side*.036],.006,'Leva che porta il pattino verso il cerchio.',silver,[`${tag}-brake-pivot`]);add(`${tag}-brake-pad-${side}`,'Pattino freno','Freni','brake','box',[x+side*.08,y-.07,side*.026],[.040,.018,.015],'Materiale d’attrito che frena sul fianco del cerchio.',{color:rubber,dependsOn:[`${tag}-brake-pad-nut-${side}`]});add(`${tag}-brake-pad-nut-${side}`,'Dado pattino','Freni','brake','cylinder',[x+side*.08,y-.07,side*.055],[.006,.009,0],'Blocca la posizione del pattino.',{rotation:[Math.PI/2,0,0]});add(`${tag}-brake-pad-washer-${side}`,'Rondella pattino','Freni','brake','ring',[x+side*.08,y-.07,side*.047],[.007,.002,0],'Distribuisce il carico sul supporto del pattino.',{dependsOn:[`${tag}-brake-pad-nut-${side}`]});}
add(`${tag}-brake-pivot`,'Perno centrale pinza','Freni','brake','cylinder',[x,y,0],[.005,.09,0],'Articolazione e fissaggio della pinza.',{rotation:[Math.PI/2,0,0],dependsOn:[`${tag}-brake-nut`]});add(`${tag}-brake-nut`,'Dado fissaggio pinza','Freni','brake','cylinder',[x,y,-.05],[.008,.008,0],'Fissa la pinza alla forcella o al ponte posteriore.',{rotation:[Math.PI/2,0,0]});add(`${tag}-brake-spring`,'Molla di ritorno freno','Freni','brake','ring',[x,y,.035],[.021,.002,0],'Riporta i pattini lontano dal cerchio quando rilasci la leva.',{dependsOn:[`${tag}-brake-pivot`]});add(`${tag}-cable-bolt`,'Vite serracavo','Freni','brake','cylinder',[x+.055,y+.015,.025],[.004,.02,0],'Blocca il cavo sulla pinza.');tube(`${tag}-cable`, 'Cavo freno', 'Freni','brake',[.84,1.53,tag==='front'?.16:-.16],[x,y+.02,.02],.0012,'Trasmette la trazione della leva alla pinza.',silver,[`${tag}-cable-bolt`]);tube(`${tag}-housing`,'Guaina freno','Freni','brake',[.84,1.53,tag==='front'?.16:-.16],[x,y+.13,.02],.004,'Contiene e guida il cavo, opponendosi alla compressione.',dark,[`${tag}-cable-bolt`]);}

export const demoStructure:Structure={id:'classic-city-demo-v1',name:'Classica · monovelocità',version:1,kind:'didactic',standards:{frame:'acciaio saldato',headset:'filettata 1 pollice',bottomBracket:'BSA a calotte e sfere',crank:'perno quadro',brakes:'pinza laterale',frontHub:'coni e sfere, asse a dadi',rearHub:'coni e sfere, asse a dadi',drivetrain:'ruota libera monovelocità',wheels:'copertoncino con camera',pedals:'revisionabili a sfere'},coverage:'Modello procedurale schematico. Raggi, nippli, sfere, viti e maglie sono selezionabili singolarmente; quantità e dimensioni sono illustrative. La ruota libera è un gruppo non aperto; non sono ricostruiti gli interni delle leve, valvole, minuterie non documentate e terminali dei cavi. Non è un inventario completo di una bici reale.',parts,procedures:recipes};
export const demoBundle:Bundle={schemaVersion:1,structures:[demoStructure],bikes:[{id:'city-demo',name:'Classica 01',brand:'Officina · didattica',category:'Città',subtype:'Monovelocità · telaio in acciaio',year:'Configurazione generica',structureId:demoStructure.id,status:'didactic',notes:'Un primo atlante per orientarti. Non corrisponde a un modello commerciale e non certifica utensili o quantità della tua bici.',color:mint}]};
