import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import ts from 'typescript';
import assert from 'node:assert/strict';
mkdirSync('.sites-runtime/check',{recursive:true});
for(const name of ['catalog','demo','glb'])writeFileSync(`.sites-runtime/check/${name}.mjs`,ts.transpileModule(readFileSync(`lib/${name}.ts`,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText.replace("'./catalog'","'./catalog.mjs'"));
const {validateBundle,matchStructures,removalPlan}=await import('../.sites-runtime/check/catalog.mjs');
const {demoBundle,demoStructure}=await import('../.sites-runtime/check/demo.mjs');
const {validateGlb}=await import('../.sites-runtime/check/glb.mjs');
validateBundle(demoBundle);
assert(demoStructure.parts.length>500);
assert.equal(matchStructures(demoStructure.standards,[demoStructure])[0].exact,false,'A didactic model must never certify a real bike');
const reference=structuredClone(demoStructure);reference.id='test-reference';reference.kind='reference';
assert.equal(matchStructures(reference.standards,[reference])[0].exact,true);
assert.equal(matchStructures({...reference.standards,bottomBracket:'unknown'},[reference])[0].exact,false);
assert.equal(matchStructures({...reference.standards,bottomBracket:'italiano'},[reference])[0].exact,false);
let invalid=structuredClone(demoBundle);invalid.structures[0].parts[0].dependsOn=['missing'];assert.throws(()=>validateBundle(invalid),/assente/);
invalid=structuredClone(demoBundle);invalid.structures[0].parts[0].dependsOn=[invalid.structures[0].parts[0].id];assert.throws(()=>validateBundle(invalid),/circolari/);
invalid=structuredClone(demoBundle);invalid.bikes[0].status='verified';assert.throws(()=>validateBundle(invalid),/verificata/);
assert.throws(()=>validateBundle({schemaVersion:1,structures:[reference],bikes:[]},[reference]),/esiste già/);
assert.throws(()=>validateGlb(new ArrayBuffer(20)),/non valido/);
assert(removalPlan('bb-spindle',demoStructure).find(p=>p.id==='crank-l'));
mkdirSync('data',{recursive:true});writeFileSync('data/catalogo-didattico.json',JSON.stringify(demoBundle,null,2));
console.log(`Catalog verified: ${demoStructure.parts.length} individually selectable elements; duplicate, incomplete match, invalid dependencies and GLB rejection checked.`);
